---
title: "Bayesian estimation of heteroskedastic ordered probit (HETOP) model"
author: 
  - name: Joon-Ho Lee (joonho@berkeley.edu)
date: "February 5, 2020"
output:
  html_document:
    toc: true
    toc_depth: 2
    number_sections: yes
    theme: journal
    highlight: haddock
    css: styles.css
    fig_caption: yes
  tufte::tufte_html:
    number_sections: yes
    toc: true
    toc_depth: 2
  pdf_document:
    toc: yes
    toc_depth: '3'
bibliography: bibliography.bib
---

```{r basic_setup, include=FALSE}
# Set working directory
setwd("~/Treatment-effect-heterogeneity/Multisite Trials/docs/HETOP model")

# Set RMarkdown options
knitr::opts_chunk$set(echo = TRUE, warnings = FALSE, message = FALSE)

# # Set Stan options
# options(mc.cores = parallel::detectCores())
# rstan_options(auto_write = TRUE)
# Sys.setenv(LOCAL_CPPFLAGS = '-march=native')

# Call libraries
library(tidyverse)
library(HETOP)
```

# Introduction




```{r}
## Define mean-centered covariates
G <- 12
z1 <- sample(c(0, 1), size = G, replace = TRUE)
z2 <- 0.5*z1 + rnorm(G)
Z <- cbind(z1 - mean(z1), z2 = z2 - mean(z2))


## Define true parameters dependent on covariates
beta_m <- c(0.3, 0.8)
beta_s <- c(0.1, -0.1)
mug <- Z[,1]*beta_m[1] + Z[,2]*beta_m[2] + rnorm(G, sd = 0.3)
sigmag <- exp(0.3 + Z[ ,1]*beta_s[1] + Z[ ,2]*beta_s[2] + 0.2*rt(G, df = 7))
cutpoints <- c(-1.0, 0.0, 1.2)


## Generate data
ng <- rep(200, G)
ngk <- gendata_hetop(G, K = 4, ng, mug, sigmag, cutpoints)
print(ngk)


## Fit FH-HETOP model including covariates
## NOTE: using an extremely small number of iterations for testing, 
##       so that convergence is not expected
m <- fh_hetop(ngk, fixedcuts = c(-1.0, 0.0), p = c(10,10), 
              m = c(100, 100), gridL = c(-5.0, log(0.10)), 
              gridU = c(5.0, log(5.0)), Xm = Z, Xs = Z, 
              n.iter = 100, n.burnin = 50)

print(m)
print(names(m$fh_hetop_extras))

s <- m$BUGSoutput$summary
print(data.frame(truth = c(beta_m, beta_s), s[grep("beta", rownames(s)),]))
print(cor(mug, s[grep("mu", rownames(s)),"mean"]))
print(cor(sigmag, s[grep("sigma", rownames(s)),"mean"]))


## manual calculation of WAIC (see help file for waic_hetop)
tmp <- waic_hetop(ngk, m$BUGSoutput$sims.matrix)
identical(tmp, m$fh_hetop_extras$waicinfo)
```





# References



