---
title: "Modeling Choices #03. Dirichlet Process"
author: 
  - name: Joon-Ho Lee (joonho@berkeley.edu)
date: "February 29, 2020"
output:
  html_document: 
    css: styles.css
    fig_caption: yes
    highlight: haddock
    number_sections: yes
    theme: readable
    toc: yes
    toc_depth: 2
  tufte::tufte_html:
    number_sections: yes
    toc: true
    toc_depth: 2
  pdf_document:
    toc: yes
    toc_depth: '3'
bibliography: bibliography.bib
---

```{r basic_setup, include=FALSE}
### Set working directory
setwd("~/Bayes-deconvolution/posts/02_Modeling choices_03_Dirichlet Process")

### Set RMarkdown options
knitr::opts_chunk$set(echo = TRUE, warnings = FALSE, message = FALSE)

### Call libraries
library(tidyverse)
library(cowplot)
library(hhsim)
library(DPpackage)
library(bspmma)


# ### Set Stan options
# # options(mc.cores = parallel::detectCores())
# rstan_options(auto_write = TRUE)
# Sys.setenv(LOCAL_CPPFLAGS = '-march=native')

### Theme settings
theme_preset <- 
  theme_bw() + 
  theme(panel.background = element_blank(),
        panel.grid = element_blank(), 
        legend.position = "bottom", 
        legend.direction = "horizontal", 
        legend.title = element_blank())
```


# The @rubin1981estimation model with Dirichlet Process prior

## The classic @rubin1981estimation model

Consider $K$ study sites in which researchers perform the same interventions and measure the same outcomes. Each site, indexed by $k$, estimates a treatment effect $\tau_k$ averaged across individuals in the site. The sites don't report $\{\tau_k\}^{K}_{k=1}$: instead, they report $\{\hat{\tau}_k\}^{K}_{k=1}$. Some of the observed variation in $\{\hat{\tau}_k\}^{K}_{k=1}$ is sampling variation, yet there is likely to be some genuine variation in effects across settings, often defined as $\sigma_{\tau}^{2} = \text{var}(\tau_{k})$. 

@rubin1981estimation considers a case in which the analyst has access to a set of estimated effects $\{\hat{\tau}_k\}^{K}_{k=1}$ and estimates of the associated sampling errors $\{\hat{se}_{\tau_k}\}^{K}_{k=1}$. Rubin specifies a relationship between the observed estimates and the unobserved $\{\tau_k\}^{K}_{k=1}$, and in addition spcifies a relationship between $\{\tau_k\}^{K}_{k=1}$ and the aggregate parameters $(\tau, \sigma_{\tau}^2)$). The @rubin1981estimation model has a hierarchical likelihood in which each site has own treatment effect parameter, $\tau_k$, but these effects are all drawn from a common distribution governed by $(\tau, \sigma_{\tau}^2)$ as follows: 


$$
\hat{\tau}_{k} \sim N(\tau_{k}, \hat{se}_{k}^2) \quad \forall k, 
$$
$$
\tau_{k} \sim N(\tau, \sigma_{\tau}^2) \quad \forall k. 
$$


## Semiparametric modeling via Dirichlet Process^[See Chapter 4.9 of @congdon2019bayesian.]

The @rubin1981estimation model is fully parametric and a particular case of a more general class of models on $G$. In the @rubin1981estimation model, inferences may depend on the assumed forms for higher level priors (e.g.,  $\tau, \sigma_{\tau}^2$), and will be distorted if there are unrecognized features such as multiple modes in the underlying second-level effects. Instead of assuming a known prior distribution for $G$ for second-level latent effects, the **Dirichlet Process (DP)** prior involves a distribution on $G$ itself, acknowledging uncertainty about its form.  


The DP prior involves (1) a base distribution $G_{0}$, the expectation of $G$, and (2) a precision or strength parameter $alpha_0$ governing the concentration of the prior for $G$ about its mean $G_{0}$. For any partition $A_1, ..., A_M$ on the support of $G_0$, the vector $\{G(A_1), ..., G(A_M)\}$ of probabilities $G(A_m)$ contained in the set $\{A_m, m = 1, ..., M\}$ follows a Dirichlet distribution $\text{Dirichlet}(\alpha_0 \cdot G_0(A_1), ..., \alpha_0 \cdot G_0(A_M))$.^[Such an approach may be termed *semiparametric* as it involves a parametric model at the first level for the observations, but a nonparametric model at the second-level.]   


Original forms of the DP prior assumed $G_0$ to be known and fixed. One problem with a Dirichlet Process when $G_0$ is known is that it assigns a probability of 1 to the space of discrete probablity measures, which means that site-level treatment effects $\{\hat{\tau}_k\}^{K}_{k=1}$ are measured exactly. An alternative is to take the parameters in $G_0$ to be unknown, and to follow a set of parametric distributions, with possibly unknown hyperparametrees, resulting in a mixture of Dirichlet Process (MDP) model:


$$
\hat{\tau}_{k} \sim N(\tau_{k}, \hat{se}_{k}^2) \quad \forall k, 
$$
$$
\tau_{k} \sim \text{DP}(G_0, \alpha_0) \quad \forall k,  
$$


where $G_0 = N(\tau, \sigma_{\tau}^{2})$, $\alpha_0 \sim \text{Gamma}(4, 4)$, $\tau \sim N(0, 100)$, and $\sigma_{\tau}^{-2} \sim \text{Gamma}(1, 1)$. This is more favorable to a more bumpy, multi-modal distribution $G$: the prior expected number of clusters of $\tau_k$'s under this DP-based model is 5.   







# References



